### ISSUE TITLE
Build and Run as Container adn Expose to My box

### ISSUE THREAD

**Issue by hhlp** [fedora-infra/asknot-ng#105]
I successfull build but I don't know how to run?

REPOSITORY                     TAG      IMAGE ID       CREATED          SIZE
localhost/asknot               latest   b08d90b615d7   28 minutes ago   660 MB

Is there any additional parameters that I've had to use:

```
podman run --name=asknot -d -p 8080:80 localhost/asknot
```
In my browser box

whacanidoforfedora.org:8080

but I can't connect.... 

Is there something I'm missing? or Doing in a inappropiate way?

kind Regards.,

**Comment by cverna** [comment]
I believe you need the --net=host flag in that podman command, to tell podman to use you host networking instead of creating a virtual bridge.

so the command would be 

```
podman run --name=asknot -d -p 8080:80 --net=host localhost/asknot
```
