### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/asknot-ng#109]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by cverna** [comment]
> Hello, the Fedora project migrates its translation platform to Weblate [1].
> 
> This tool directly interact with your git repository, and requires us to know:
> 
>     * [mandatory] which branch is your development branch?
develop
> 
>     * [mandatory] have you merged latest translation from Zanata and locked the project?
no
> 
>     * [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
> 
>     * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
> 
>     * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
> 
>     * [optional] do you need us to activate any specific checks? (this is a setting per component [3])
> 
>     * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)
> 
> 
> Please note:
> 
>     * For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
> 
>     * In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
> 
>     * You can change your mind over time, just reach [trans@lists.fedoraproject.org](mailto:trans@lists.fedoraproject.org)
> 
> 
> [1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/
> [2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
> [3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Jibec** [comment]
Le 2020-01-06 13:51, Clement Verna a écrit :
>> * [mandatory] have you merged latest translation from Zanata and
>> locked the project?
> 
> no

please just merge latest translations and lock the project.
I have everything I need to migrate your project.

**Comment by cverna** [comment]
> Le 2020-01-06 13:51, Clement Verna a écrit :
> > * [mandatory] have you merged latest translation from Zanata and > locked the project? no
> please just merge latest translations and lock the project. I have everything I need to migrate your project.

I have no idea on how to do that, I also don't think that I am the maintainer of this project in Zanata so I probably cannot lock it :P

**Comment by Jibec** [comment]
Owner is ralph: https://fedora.zanata.org/project/view/asknot-ng/people
Pulling existing translations is easy, would you like me to open a PR?

**Comment by cverna** [comment]
> Owner is ralph: https://fedora.zanata.org/project/view/asknot-ng/people Pulling existing translations is easy, would you like me to open a PR?

Yeah that would be great :)

@ralphbean would you be able to lock the project on zanata ?

**Comment by Jibec** [comment]
sorry, I could have done only one PR, do not hesitate to squash it if this matters to you.

I've tried to update pot file, but the script fails. When is the last time you updated it?

**Comment by Jibec** [comment]
Kind remember, I don't know how to fix the pot issue, it requires your attention.

**Comment by cverna** [comment]
@Jibec what was the error  ? and the steps you have followed ?

**Comment by Jibec** [comment]
I followed the readme: 
https://github.com/fedora-infra/asknot-ng#preparing-translations

The python script failed, telling me a path or parameter was missing.
But if this works for you, just commit the generated pot.

**Comment by cverna** [comment]
Fixing the script https://github.com/fedora-infra/asknot-ng/pull/112

Update pot file https://github.com/fedora-infra/asknot-ng/pull/113

**Comment by cverna** [comment]
@Jibec it should be all done now.

**Comment by Jibec** [comment]
Done: 
https://translate.stg.fedoraproject.org/projects/fedora-infra/asknot-ng/

cverna is admin.

Weblate will update po files automatically

**Comment by cverna** [comment]
Thanks @Jibec, closing this now
