### ISSUE TITLE
What websites are we translating, and what is the deployement frequency?

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/asknot-ng#115]
If I understand correctly, in the https://github.com/fedora-infra/asknot-ng/tree/develop/questions folder:

- https://github.com/fedora-infra/asknot-ng/blob/develop/questions/gnome.yml is http://gnome.schuirmann.net
- https://github.com/fedora-infra/asknot-ng/blob/develop/questions/coala.yml is http://coala.schuirmann.net
- https://github.com/fedora-infra/asknot-ng/blob/develop/questions/fedora.yml is https://whatcanidoforfedora.org

Translating gnome.yml and coala.yml is worth translating only if published, so I suggest to remove it from pot file.

Second question, what is the delay after merging new translations? This was merged two days ago: https://github.com/fedora-infra/asknot-ng/pull/114 but I can't see the changes in the website. Do you have to manually trigger a deployment?

**Comment by cverna** [comment]
> If I understand correctly, in the https://github.com/fedora-infra/asknot-ng/tree/develop/questions folder:
> 
>     * https://github.com/fedora-infra/asknot-ng/blob/develop/questions/gnome.yml is http://gnome.schuirmann.net
> 
>     * https://github.com/fedora-infra/asknot-ng/blob/develop/questions/coala.yml is http://coala.schuirmann.net
> 
>     * https://github.com/fedora-infra/asknot-ng/blob/develop/questions/fedora.yml is https://whatcanidoforfedora.org
> 
> 
> Translating gnome.yml and coala.yml is worth translating only if published, so I suggest to remove it from pot file.

Can you create an independent issue for that ? 

> 
> Second question, what is the delay after merging new translations? This was merged two days ago: #114 but I can't see the changes in the website. Do you have to manually trigger a deployment?

We have a production and staging branch that trigger a deployment in each environment. I have merged the latest develop to these 2 branches so the new translation should be available now.
