### ISSUE TITLE
German version of the site is broken

### ISSUE THREAD

**Issue by mymindstorm** [fedora-infra/asknot-ng#121]
https://whatcanidoforfedora.org/de/

```
Error: Syntax error, unrecognized expression: #das-webseiten-team. jquery-2.1.3.min.js:2:12467
    jQuery 7
    hashSelect https://whatcanidoforfedora.org/de/static/js/site.js:10
    each jQuery
    hashSelect https://whatcanidoforfedora.org/de/static/js/site.js:9
    <anonymous> https://whatcanidoforfedora.org/de/static/js/site.js:34
    jQuery 4
```

**Comment by mymindstorm** [comment]
There was a trailing period on [this string](https://translate.fedoraproject.org/translate/fedora-infra/asknot-ng/de/?q=+Websites+Team&checksum=&offset=1#history). Should be fixed when weblate syncs.

**Comment by cverna** [comment]
This was fixed in production and staging, thanks again for looking after that :-)
