### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by comzeradd** [fedora-infra/asknot-ng#16]
What will be used for localization? I did the first implementation work on the original project for using webL10n javascript library. I could help adding it here too.

**Comment by ralphbean** [comment]
Hey!  I cooked up my own thing that I _think_ works pretty well.

You can extract a `.pot` file with the commands mentioned here:  https://github.com/fedora-infra/asknot-ng#preparing-translations

Then I was going to push that to zanata to get translated `.po` files back.

When those get compiled in `.mo` files, the `asknot-ng.py` script will find those and generate distinct copies of the site for each language.

There is then a "Languages" menu on each page that will let you navigate to each different page.

If you have ideas about how to improve any of those pieces, I'd love the help.

**Comment by sils** [comment]
Related: I'd recommend using rultor for merging PRs and automatically upload translations to zanata in the rultor script. If you also use rultor to make releases you can automatically deploy the page and pull translations from zanata before doing that - a fully automated workflow. We've set up this for coala-analyzer/coala and it's awesome, contact me if you want that so I can help.

**Comment by sils** [comment]
related bug: https://github.com/fedora-infra/asknot-ng/issues/27

**Comment by ralphbean** [comment]
I'd say a tentative "no" to rultor for now.  We share the same :+1: review process across all the fedora-infra repos, so we'd need to talk about it more to make sure the team's on board.  It's not open source, is it?  That's not a blocker (we're using GitHub) but we're trying to minimize our proprietary tools (see https://pagure.io).

**Comment by sils** [comment]
Rultor is open source, otherwise I wouldn't recommend it. We're trying hard
to switch to gitlab btw. but the lack of hosted continuous integration
makes it hard. Rultor is at https://github.com/yegor256/rultor/ .

2015-08-15 18:43 GMT+02:00 Ralph Bean notifications@github.com:

**Comment by hhlp** [comment]
I recommend close this ticket:

@cverna 

regards.,
