### ISSUE TITLE
The "i'm interested" and "not interested" (green and pink buttons) move around as you're clicking

### ISSUE THREAD

**Issue by halfline** [fedora-infra/asknot-ng#18]
= bug description =
The "i'm interested" and "not interested" (green and pink buttons) move around as you're clicking.

= bug analysis =
The buttons change size so they jump around.

= fix recommendation =
It would be good if the left button was right aligned to the center of its parent and the right button was left aligned (so the gap between them never moves)

**Comment by Sadin** [comment]
Im looking into it.

**Comment by Sadin** [comment]
Do we have a problem with stacking the buttons like [whatcanidoformozilla ](http://whatcanidoformozilla.org) does? I personally like it a lot better, but that's just my opinion.

Example:
![Example Image](http://i.imgur.com/6hKWkjc.png)

**Comment by Sadin** [comment]
@ralphbean The above addresses the "mis-click" due to the varying button sizes due to the messages within them. 

Another note: Stacking the buttons will look a lot nicer from a mobile-first perspective, imo.
