### ISSUE TITLE
No convenient way to go back after accidentally click "not interested"

### ISSUE THREAD

**Issue by halfline** [fedora-infra/asknot-ng#19]
If i'm quickly cycling through the categories and accidentally click not interested on one that i want to dive into, i have to cycle all the way through them again.

I think a slight improvement to the user experience would be to put back and forward triangles on the left and right side (respectively) of the inset category description

**Comment by halfline** [comment]
Note, these triangles wouldn't replace the "not interested" button, but supplement it.  the left triangle would go back, and the right triangle would do the same thing as the "not interested" button.

**Comment by Sadin** [comment]
You essentially want an "oops, take me back button" which can be done. I dont think arrows would be a good idea though, that's just my personal opinion.

**Comment by ralphbean** [comment]
I'd add that I'm using the html5 `.pushState` stuff in there which was _supposed_ to let you use the back button in your browser.  But I'm not sure it's working.

**Comment by ralphbean** [comment]
Should be fixed by #62.  Thanks @cydrobol!
