### ISSUE TITLE
Text overlap in mobile view

### ISSUE THREAD

**Issue by Sadin** [fedora-infra/asknot-ng#22]
Some things still tend to overlap on smaller devices, or run off screen in portrait orientation.
I will play around with various viewports, scale text down accordingly, and check spacing, as I believe that's the issue.

Some examples:
![Example A](http://i.imgur.com/ZfBbKnT.png)
![Example B](http://i.imgur.com/kxZesfU.png)

**Comment by justwheel** [comment]
It was noted in a channel this morning that this issue might also be related to accessibility issues, like if a person is browsing the site on a normal browser while zoomed in very high. Solving this issue might also help make it easier for people with vision problems who are visiting the site.

**Comment by jschwarzwalder** [comment]
Another instance of text overlap.
![screenshot_2016-06-11-02-08-38_1024](https://cloud.githubusercontent.com/assets/8946787/15994297/2bbbd246-30b5-11e6-9eb4-8341290130af.png)

Is there a known solution?

**Comment by vharsh** [comment]
Text overlap, screenshots
Test system details
Fedora-24 workstation running on 1366X768 resolution laptop without zoom.
URL:[ WhatCanIdoForFedora > Java > Java Special Interest group](http://whatcanidoforfedora.org/en/#coding#java#java-special-interest-group)

**Firefox 48.0.1** Size of the body element = 1366 X 633
![screenshot from 2016-09-10 06-17-16](https://cloud.githubusercontent.com/assets/9304050/18406761/f265f066-771e-11e6-84af-169f404162eb.png)
**Google Chrome Version 53.0.2785.101 (64-bit)** Size of the body element = 1366 X 675
![screenshot from 2016-09-10 06-36-37](https://cloud.githubusercontent.com/assets/9304050/18406872/f89093f4-7720-11e6-94c4-5dd71ce7284e.png)

Reducing the title to "JAVA SIG" to could be a quick fix to this issue for various device sizes.
Chrome's device emulation showed the title text in four lines if device was set to Galaxy S5.

**Comment by Sadin** [comment]
I really believe the core of this issue is due to a lot of floating/hard positioned elements clashing because of this default theme being a modified Bootstrap Example theme. Im going to be taking a look again into this.

**Comment by hhlp** [comment]
Your issue is to old, the site was suffer some change across the time and your issue could be obsolete, if you problem come again, feel free to open a new one.

**Comment by Sadin** [comment]
Closing. Reopen if still relevant.
