### ISSUE TITLE
Gestures

### ISSUE THREAD

**Issue by Sadin** [fedora-infra/asknot-ng#24]
As we adjust the application to work/look better in mobile ( see issue: #22 ), would possibly like to further mobile support by adding gesture events with http://hammerjs.github.io/ ?

Example: Swipe Left to quickly go back, right to see the next option, up to go down a level and learn more, or swipe down to go back to the top level if possible.

**Comment by cydrobolt** [comment]
IMHO I don't think we should add gestures. I've had a relatively bad experience with them, and they glitch up or cause unintended actions.

I try to avoid them as much as possible, even switching to desktop mode in order to read something without getting taken off the page.

**Comment by Sadin** [comment]
@Cydrobolt hey thanks for your input! The idea just dawned on my while I was working on something else and thought it couldn't hurt to ask.

**Comment by ralphbean** [comment]
I don't have any experience with gestures/hammerjs (good or bad), so I can't really comment.

I guess I'll go ahead and close this for now?  Please re-open if there's further discussion!
