### ISSUE TITLE
Add compile script

### ISSUE THREAD

**Issue by sils** [fedora-infra/asknot-ng#31]
Would be nice to be able to compile a question theme combination with just one command including translations. I see no need for copying five dumb commands again and again when a single python script with a few params could do the job.

**Comment by ralphbean** [comment]
Yes, this would be nice to have.

**Comment by ralphbean** [comment]
Noting here that we have a shell script that only does the translation compilation here:  https://github.com/fedora-infra/asknot-ng/blob/develop/compile-translations.sh

**Comment by termdew** [comment]
I guess that "asknot-ng.py" does the job already..

**Comment by cverna** [comment]
Let's close this then :-)
