### ISSUE TITLE
Visual problem in default theme

### ISSUE THREAD

**Issue by sils** [fedora-infra/asknot-ng#36]

**Comment by sils** [comment]
sorry, github understood something else when I pressed enter accidentally, dewscription follows shortly.

**Comment by sils** [comment]
The screenshot below appears for me when I generate the coala questions with the default template from current master:

![screenshot from 2015-08-15 18-58-53](https://cloud.githubusercontent.com/assets/5716520/9289941/b89fcb32-437f-11e5-82ce-7b8725435ca0.png)

As you can see the right half of the exclamation mark is cut off. This also happens to other chars and questions but it is not that obvious there. So this is probably some css problem.

**Comment by termdew** [comment]
Not happening in the latest develop branch, can be closed.
![visuals](https://user-images.githubusercontent.com/23658248/66421243-c9a1b700-ea07-11e9-9b3b-b326605a693b.png)

**Comment by hhlp** [comment]
Your issue is to old, the site was suffer some change across the time and your issue could be obsolete, if you problem come again, feel free to open a new one.
