### ISSUE TITLE
Image Licensing

### ISSUE THREAD

**Issue by sils** [fedora-infra/asknot-ng#41]
Uhm, I introduced the fedora background image, not sure how that one's licensed, maybe it needs to be mentioned? I hate licensing.

**Comment by puiterwijk** [comment]
Well, if you do not do licensing, the FPCA (https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement) gets into effect, which for content says: CC-BY-SA supplemented by Moral Rights Clause Waiver and GPL Relicensing Permission.

Disclaimer: IANAL, someone else might have better info, but this is what the FPCA is for.

**Comment by sils** [comment]
Well IANAL too and since we're using our own stuff I don't think it'll be that much of a problem, still we should probably attribute the images in the README or so to be sure and point out from where they're taken, that they're CC licensed?

This also applies to https://github.com/fedora-infra/asknot-ng/pull/50 .

**Comment by ralphbean** [comment]
@sils1297 where did you get the background image?  That would help to track down attribution.

**Comment by sils** [comment]
@ralphbean tbh I installed fedora and there's a "backgrounds" directory somewhere containing those images...

**Comment by ralphbean** [comment]
We'll have to ping the Fedora design-team next.  They'd have more information.

**Comment by ralphbean** [comment]
Thanks to a pointer from @sadin, it looks like the wallpaper is [this one](https://fedoraproject.org/wiki/F22_Artwork) by @ryanlerch!

**Comment by Sadin** [comment]
Good thing I store class notes on github and I saw this :+1:

**Comment by ryanlerch** [comment]
If it is this one -- https://fedoraproject.org/wiki/File:F22_alpha_wp.png -- then it is def CC licenced :) -- feel free not to have to attribute me either, TBH :)

**Comment by Sadin** [comment]
Is this okay to be closed?

**Comment by ralphbean** [comment]
We should probably add a note to the README about the license status and then call it closed.

**Comment by ralphbean** [comment]
Fixed by @Sadin in #56.
