### ISSUE TITLE
Compress fedora bg image

### ISSUE THREAD

**Issue by sils** [fedora-infra/asknot-ng#43]
takes too long to load on whatcanidoforfedora.org and is an unpleasant experience.

**Comment by sagarhani** [comment]
@sils1297 The current size of background image is 1.4 MB (1,420,123 bytes).
Shall I reduce it to 100 KB ?
Page will load faster and quality of the image looks the same.

**Comment by sils** [comment]
I also noticed that - would be great. Could you also do this for the coala
background image?

Thanks.

**Comment by sagarhani** [comment]
@sils1297 Sure. :+1: 
Shall I reduce the coala background image to 100 KB ?

**Comment by sils** [comment]
Sure, let's see how that looks.

**Comment by sagarhani** [comment]
@ralphbean Do I need to reduce the size of coala background image also?

**Comment by ralphbean** [comment]
If you'd like to, yes.  I think they would appreciate it :)

**Comment by sils** [comment]
We would of course :)

2015-09-22 17:56 GMT+02:00 Ralph Bean notifications@github.com:

**Comment by sagarhani** [comment]
Done. :+1:

**Comment by sils** [comment]
@sagarhani many thanks!
