### ISSUE TITLE
Add option to turn off l10n

### ISSUE THREAD

**Issue by sils** [fedora-infra/asknot-ng#49]
We don't really want that for e.g. coala, because it refers to english pages anyways sooner or later.

**Comment by Jibec** [comment]
Hi, why would you do that ?
You may write that this project is working in English only, won't it be sufficient ?

**Comment by sils** [comment]
There's a menu allowing the user switching languages, that doesn't work well without translations.

**Comment by Jibec** [comment]
The menu on the bottom right with "Change Language" ? The only issue I see is loosing the anchors. Can you please more description about the issue ?
Note : what is coala ?

**Comment by Jibec** [comment]
oh... I just understood, asknot-ng is the source code of an app that is use to make "whatcanidofor***" website.
And here, we have one depot mixing the app source and the different instances of the app. I assume it's for maintenance reason. @ralphbean would it be possible and good to make one repository for the app source code and one for each instance ? Include whatcanidoforfedora in current website scheme would also give a more consistent access to content to translation teams (cf my request issue).

**Comment by Sadin** [comment]
Closing for now. Reopen if pressing.
