### ISSUE TITLE
Make openShift configuration environment dependent

### ISSUE THREAD

**Issue by sils** [fedora-infra/asknot-ng#54]
We'd like to ship the whatcanidoforgnome.org website with openshift too and the best thing to do is probably to also use this repository and mane the choice of theme and question set dependent on environment variables defined in the OPenShift environment.

I'll probably look into that this weekend, if anyone has a bit more openShift knowledge and knows how we can do this best I'd of course appreciate a comment!

(Related: https://github.com/fedora-infra/asknot-ng/issues/53)

**Comment by ralphbean** [comment]
I aimed to be able to do this already, so hopefully it will just work.

You should be able to set environment variables on your openshift app, and asknot-ng should look for them in the `.openshift/action_hooks/build` script.  Take a look at the `ASKNOT_THEME` var there for an example.

**Comment by sils** [comment]
Ah that is awesome! Will close this as soon as it works :) Thanks!

2015-10-28 18:26 GMT+01:00 Ralph Bean notifications@github.com:

**Comment by sils** [comment]
Do you deploy to a DIY cartridge, like:

rhc app create askgnome diy --from-code
https://github.com/fedora-infra/asknot-ng

2015-10-28 19:06 GMT+01:00 Lasse Schuirmann lasse.schuirmann@gmail.com:

**Comment by ralphbean** [comment]
Yes.  It has been a while since I set it up and I'm no OpenShift expert, but that looks correct to me.

**Comment by sils** [comment]
Ah, for that to work smoothly you'll probably want to reset master to
develop after all, otherwise people trying this will only get a 503.

2015-10-28 19:22 GMT+01:00 Ralph Bean notifications@github.com:
