### ISSUE TITLE
[l10n] please automatically push content from Fedora.Zanata

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/asknot-ng#69]
Hi, can you please update regularly content from Zanata like other Fedora Websites ?
As this website strings are very context related, it's easier for us to see progress and check the correctness of translation.

In the meanwhile, if this task isn't trivial, can you manually push all po file from every languages ? I wrote an email to "trans" ml, and we have now 2500 new words translated.

Thanks a lot for your help !

**Comment by ralphbean** [comment]
I'm not sure how we would go about doing this automatically.

The site is served from openshift.  We could do it with a cronjob on sundries01 to:
- clone from github
- pull from zanata
- commit
- push to github
- push to openshift
- remove the local checkout

And.. that could do it.  Say, once a day?

**Comment by Jibec** [comment]
great new !

I don't know the origin of this, but other Fedora Website are updated twice a day. May you do the same so contributors don't get confused ?
You may have some information about this website in https://fedoraproject.org/wiki/Websites/workflow or you may talk with robyduck

In the same time, it would be great if you can take the opportunity to give a more explicit project name in Zanata. What we are translating is whatcanidoforfedora.org and not asknot-ng.

I would suggest : 
- project name : whatcanidoforfedora or asknot-whatcanidoforfedora
- version name : whatcanidoforfedora.org (same pattern as Websites) or master

thanks again for your help

**Comment by phracek** [comment]
Let us know if you need a help from Fedora Developer Portal team.
We would be happy if Spanish, Portuguese or Czech is available. And of course the rest.

**Comment by Jibec** [comment]
@phracek , I'm sorry but it's a misunderstanding. I gave a few advice for asknot-ng about translation and invited you to have a look.
We should only discuss asknot-ng in here.

**Comment by Jibec** [comment]
@ralphbean : we finished french translation, can you please push content to the website please ?
I don't have any idea about the complexity of automation, if this is coming in the next days or in the month, we can wait. Please let me know so I don't bother you for a time.

**Comment by ralphbean** [comment]
French translation being pushed now.

Automation is likely not too complicated.  It would require:
- [ ] Writing a simple cronjob.
- [ ] Installing that on `sundries01`.
- [ ] Creating a new ssh key pair for that task.
- [ ] Uploading the public key to openshift.

**Comment by jaaf** [comment]
@ralphbean 
Hi, thank you for your help. 
I don't know if you had time enough to do what is proposed above but something strange is happening. 
I translated the whole site more than a week ago. Since I waited for a new updating of the site. Today I checked it once again. The site appears to have been updated  as some translated sentences have been changed. But, strangely,  a lot of already translated sentences still appear in English. Could you confirm me that the po file have been pushed recently?
.

**Comment by Jibec** [comment]
@ralphbean can we plan to have a manual push in the next days, before release of F24 ?
If so, it would be great to send and email to trans@ so teams know (tell me if you wish me to do it)
thanks for your help !

**Comment by Jibec** [comment]
I think this have been done a long time ago, thanks again
