### ISSUE TITLE
"Fedora Infrastructure Apps" is cannot scrolled, therefore some button cannot be clicked.

### ISSUE THREAD

**Issue by ghost** [fedora-infra/asknot-ng#72]
At "Fedora Infrastructure Apps" list of this asknot, the lower side of list is out of the screen. Therefore it can not be selected.
![screenshot from 2016-05-20 11-20-41](https://cloud.githubusercontent.com/assets/17140762/15415329/ef782fc2-1e7c-11e6-87e5-f5b7ec783110.png)

If I disable the web-browser menu-bar, then the lower side of list is inside this screen, therefore it can be selected.
But if I enable the web-browser menu-bar, then the lower side of list is out of the screen, therefore it cannot be selected.

**Comment by Sadin** [comment]
Im looking into this as well as other UI related issues this week.

**Comment by termdew** [comment]
I think, that this issue is not relevant anymore, as issue #100 suggests the removal of fedmenu.

**Comment by cverna** [comment]
Yes let's close that, thanks @lightlace for looking at that.
