### ISSUE TITLE
Why there is the underline under the Home's button.

### ISSUE THREAD

**Issue by ghost** [fedora-infra/asknot-ng#74]
There is an underline under the Home's button.

![screenshot from 2016-05-25 13-55-02](https://cloud.githubusercontent.com/assets/17140762/15528716/7227cc90-2281-11e6-9627-2f95d11e0009.png)
(Because of description, I added red color drawing to the screenshot.)

I guessed that the line is displaying that currently status of this page. 
But, though I clicked "Totaly" etc and the status of page changed from Home to another , the underline remains under the "Home" button. 

Or if the underline is to tell that there is a button above this line, 
at this case, no line under the "Get Fedora" button is contradiction.

**Comment by Sadin** [comment]
Gonna look at this, this is residual code from the base theme we based asknot-ng's theme off of.
