### ISSUE TITLE
Add something on the lines of "want to speak to a human? Head to fedora-join!"

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/asknot-ng#75]
We're trying to get newbies to come to the fedora join channels which were set up for this very purpose. Having it on whatcanidoforfedora would really help.

https://fedoraproject.org/wiki/Fedora_Join_SIG

**Comment by sanjayankur31** [comment]
Hi! @Sadin - any thoughts on how this would work?

**Comment by sanjayankur31** [comment]
I was wondering if a "Speak to a human" link on each "page" that we could redirect to the respective team's chat channel possibly would work to start with?

**Comment by Sadin** [comment]
Sure, this makes sense to me but here are some thoughts. 

Currently, each option that is presented to a user has a link to documentation on how to join and start contributing. Im all for lowering the barrier of entry, thats what this website does, but I worry if this will create a "feedback loop" so to speak.

If we get people directly in to IRC, more than likely what will happen is:

- They will be linked to the "getting started" for that group by a member anyway
- They will not get an answer and become impatient and leave

IRC in fedoras case, while more interactive and responsive than reading a website with links, has a lot of idle users depending on the SIG/Group until some form of meeting or planned discussion is taking place. ( From my experience anyway ) 

I'd love to hear @ralphbean 's take on this.

**Comment by ralphbean** [comment]
That's valid @Sadin, but I figure a link in the footer couldn't hurt.  If it overpowered the central question/answer content, that would be a different story I guess.

**Comment by ralphbean** [comment]
Oh, I misread.  When I wrote the above, I was thinking about putting a static link to the Join SIG in the footer.

I see now the suggestion about putting a dynamic link to each sub-team's IRC channel on each node of the Q/A tree.  That might get a little crowded in the UI... plus it would drop people into those ephemeral chat client where they would join, ask a question, and then quit before anyone can answer.  I think I agree, that might pose a UX problem for both the current contributors and the newcomers.

**Comment by Sadin** [comment]
@ralphbean exactly, I remember how it was when I joined a group. I foresee this loopback occurring. Not to mention the UI Is already cluttered on smaller resolutions.

Id like to open a ticket to revise the UX to work on more device types if thats cool?

**Comment by sanjayankur31** [comment]
I'd take a static link in the footer to the Join SIG's channels too.

While I do understand your concerns about the "loop", that applies to folks who are experienced/confident enough to know where they want to contribute. For people who are not, speaking to a human is more useful - it makes them feel at ease. So, a link to the Fedora Join IRC channel would be nice to begin with.

Once the hubs hit prod, I'd  assume the current links to "onboarding" wiki pages would be updated to point to the various team hubs? (Which as I understand will show IRC/ML/Tasks etc. cleanly in one place)

**Comment by Sadin** [comment]
There are two parts to my concern, you nailed the first part right on the head.

While I understand speaking to a human is what they want, its more useful, and it puts them at ease, there is still the fact of not all IRC channels are considered equal in terms of activity/use. The nature of new people, more often than not, who are not experienced or confident is to join IRC not get a response in what they deem an acceptable amount of time and then leave discouraged. That is WHY the very wiki pages exist. They provide a process.

That being said, I think we should down the road have this option available. But NEW people who are inexperienced generally speaking are not looking to IRC initially. IRC is old, clunky, and can be viewed by potential new people as a barrier of entry in itself.

So im going to open a Design ticket, assign it to myself, and work on a more polished UI in terms of layout and spacing. This way it fixes other issues with asknot-ng having overlapping UI components in smaller viewports, and we can start providing access to these elements like IRC, @sanjayankur31  that you are suggesting, so those who want them can use them!

Does that sound like a decent plan of attack?

**Comment by hhlp** [comment]
Your issue is to old, the site was suffer some change across the time and your issue could be obsolete, if you problem come again, feel free to open a new one.
