### ISSUE TITLE
whatcanidoforfedora.org don't have brazilian portuguese language option

### ISSUE THREAD

**Issue by fredhgl** [fedora-infra/asknot-ng#77]
Hi, 
on getfedora.org we have a option to change the language on "America" for "português do Brasil" that redirects to ".../pt_BR/" translated version.
On whatcanidoforfedora.org we don't have "português do Brasil" option anywhere.
Also can you make an autodection of the language like getfedora.org?
Thanks and sorry to bother you.

**Comment by ralphbean** [comment]
I just pulled the latest translations from zanata in #78.

Can you check http://whatcanidoforfedora.org/pt_BR/ to see if it looks right?

**Comment by Sadin** [comment]
Closing for now. Please feel free to reopen if not fixed @fredericolima

**Comment by fredhgl** [comment]
@ralphbean 
in whatcanidoforfedora.org we can't select portuguese from Brazil, just portuguese from Portugal.
In getfedora.org we can select it from America
<img width="960" alt="ptbr" src="https://user-images.githubusercontent.com/16179881/38463413-ccedf140-3ad0-11e8-93b4-752cfc5a1e3f.png">
can you fix this?
