### ISSUE TITLE
Missing glyphs in Fedora theme for Hungarian

### ISSUE THREAD

**Issue by meskobalazs** [fedora-infra/asknot-ng#80]
Right now the Fedora theme uses the "Open Sans" font, which is good, but it is missing the "ő" and "ű" glyphs, which leads to a not-so-nice result. What could we do to remedy the situation?

The page looks like this right now:
![Screenshot about](https://user-images.githubusercontent.com/9340769/28591673-cc7bcbf6-7186-11e7-8b1c-478ad3d9464e.png)

The "ő" really looks out of place.

**Comment by meskobalazs** [comment]
Switching the included `open-sans.ttf` to the Latin Ext version from Google Fonts works, but we should try to find a solution which works for everyone else too.

**Comment by hhlp** [comment]
Your issue is to old, the site was suffer some change across the time and your issue could be obsolete, if you problem come again, feel free to open a new one.

**Comment by meskobalazs** [comment]
Does your PR fix this? Otherwise I do not see why this is would be obsolete.

**Comment by hhlp** [comment]
yes I've updated Monserrat and Open Sans from STATIC to UPSTREAM.

https://fedoraproject.org/wiki/Logo/UsageGuidelines#Fonts
https://fedoraproject.org/wiki/Montserrat_Fonts
https://fedoraproject.org/wiki/Open_Sans_fonts

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">  
```

However is the problem persist will be a FONT isuses and not an Aplication issue....

Regards.,
