### ISSUE TITLE
Button overlaps footer on smaller displays

### ISSUE THREAD

**Issue by pwnfoo** [fedora-infra/asknot-ng#83]
Screenshot : 
![screenshot from 2017-08-31 11-14-03](https://user-images.githubusercontent.com/9546091/29930867-a26e242a-8e3d-11e7-8297-684ac65ad43a.png)

Screen Resolution: 1366x768

**Comment by Sadin** [comment]
Working on this issue this week as well.

**Comment by termdew** [comment]
Tried to reproduce it today, but there is no overlap happening anymore.
Issue can therefore be closed, i guess.

![askbot-ng](https://user-images.githubusercontent.com/23658248/66328044-3182cf80-e92c-11e9-97a1-4d6ecae9c5e0.png)

**Comment by p4r4xor** [comment]
May I work on this issue? Can reproduce this now.
Resolution: 1366 X 768
![Screenshot from 2020-02-17 21-22-42](https://user-images.githubusercontent.com/49688892/74668685-bed40b80-51cb-11ea-98e9-a805b38fc50c.png)

**Comment by pwnfoo** [comment]
@p4r4xor Feel free to send PRs. I'm sure someone will look at it.

**Comment by cverna** [comment]
Yes I ll be happy to review a PR :-)

**Comment by Sadin** [comment]
Back in action :) I can take a look as well.

**Comment by hhlp** [comment]
Your issue is to old, the site was suffer some change across the time and your issue could be obsolete, if you problem come again, feel free to open a new one.
