### ISSUE TITLE
Relocate asknot-ng to Pagure.io?

### ISSUE THREAD

**Issue by Sadin** [fedora-infra/asknot-ng#91]
@ralphbean @stickster thoughts?

**Comment by stickster** [comment]
I don't have an opinion on this, but I think the issue should state what problem this aims to solve.

**Comment by ralphbean** [comment]
Ditto :)  @Sadin, if you want to own `asknot-ng` (and you can!) and if you'd rather work out of pagure.io, by all means go for it.

**Comment by stickster** [comment]
Agreed, if the problem is "nobody's working on this, and I want to," it should be wherever that person wants to work. 👍

**Comment by Sadin** [comment]
Alrightly then, Its not my project. But its one I care about so Im hard at work fixing issues that are open. I wanted some third party opinions on wether or not we should or NEED to move it to pagure. Thanks guys!
